runtime: nodejs14

env_variables:
  ACCOUNT_SID: ***REMOVED***
  AUTH_TOKEN: ***REMOVED***
  WORKSPACE_SID: ***REMOVED***
  PHONE_BASE: ***REMOVED***
  AIRTABLE_DELAY: 900000
  AIRTABLE_API_KEY: ***REMOVED***
  AIRTABLE_VM_PHONE_BASE: ***REMOVED***
  TWILIO_TASKROUTER_VM_SID: ***REMOVED***
  # ENABLE_VM: REPLACE_ME_OPTIONALLY
  # ENABLE_VM_ENGLISH_TRANSCRIPTION: REPLACE_ME_OPTIONALLY
  ENABLE_ANSWER_MACHINE_DETECTION: false
  HOST_NAME: phone.mutualaid.nyc
  CALLER_ID: +16464378080
