runtime: nodejs14

env_variables:
  ACCOUNT_SID: ACfcb9a7c92c045ab2a5d16f7ec6934d06
  AUTH_TOKEN: f2bf503a8080b80ca1e341be5718a012
  WORKSPACE_SID: WS6a07b9fd3a3f366b5effbe0279cb2c66
  PHONE_BASE: appNkOcYtV1x1BIL8
  AIRTABLE_DELAY: 900000
  AIRTABLE_API_KEY: keysHQqECQ43N0L5x
  AIRTABLE_VM_PHONE_BASE: appruig4g0yGuPC39
  TWILIO_TASKROUTER_VM_SID: WK5bee2c0b94bd5956a5a5d179355fd90a
  # ENABLE_VM: REPLACE_ME_OPTIONALLY
  # ENABLE_VM_ENGLISH_TRANSCRIPTION: REPLACE_ME_OPTIONALLY
  ENABLE_ANSWER_MACHINE_DETECTION: false
  HOST_NAME: phone.mutualaid.nyc
  CALLER_ID: +16464378080
