name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true
          AIRTABLE_DELAY: 900000
          AIRTABLE_DEV_PHONE_BASE: appXtRafWpqSDGZIU
          AIRTABLE_PROD_PHONE_BASE: ***REMOVED***
